### ISSUE TITLE
Migrate to Swift 4.2 (and having problems building locally)

### ISSUE THREAD

**Issue by JeanAzzopardi** [dangthaison91/RxTextureDataSources#28]
I'm trying to use this project in another swift 4.2 project (via Pods), and it has some syntax that needs to be updated to support swift 4.2

I'm trying to build locally and submit a P.R. but I am running into issues with missing xcconfig files which is preventing me from building locally.

![image](https://user-images.githubusercontent.com/5838/46430272-d3377580-c748-11e8-9f2a-b06ad7752f45.png)

**Comment by dangthaison91** [comment]
I see @fumito-ito commit new branch to support Xcode 10 and update dependencies to the newest version? Could you take a look at that branch?

**Comment by JeanAzzopardi** [comment]
Still have an issue with opening the xcconfigs in Xcode in that branch.

![image](https://user-images.githubusercontent.com/5838/46464465-b772b480-c7c6-11e8-9b2e-134e9fc5bc15.png)

I think these are from https://github.com/jspahrsummers/xcconfigs - not sure why they aren't checked in though.

**Comment by fumito-ito** [comment]
@JeanAzzopardi Thanks for your feedback. I'm trying to convert RxASDataSources to accept Xcode 10.0 and Swift 4.2 in `feature/Xcode10` branch. But it's just in progress because I don't know about Cocoapods well.

If you can switch to Carthage, please use my fork at https://github.com/fumito-ito/RxASDataSources. It's not for Cocoapods, but work well with Carthage.

**Comment by buithuyen** [comment]
How about this problem. I have the same one

**Comment by dangthaison91** [comment]
Hi guys, version 0.4.1 now support Swift 5.0.
